---

port: 4000
host: 0.0.0.0
safe: false

### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: pygments

### content configuration ###
title:       "dartlang - Dart plugin for Atom"
keywords:    "Dart, Atom, dartlang, IDE"
description: "A Dart plugin for Atom."
source_link: "https://github.com/dart-atom/dartlang.git"
favicon:     #put a path like: "img/favicon.ico"
touch_icon:  #put a path like: "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)

### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  gray:      '#ccc'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
