name: atom_dart
version: 0.0.1
description: An experimental Dart plugin for Atom.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/atom-dartlang-experimental

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  logging: ^0.11.0
  analysis_server:
    git:
      url: git://github.com/lukechurch/dart-analysis-server-temp-working.git
      ref: v1-11-0
dev_dependencies:
  grinder: ^0.7.0
  test: ^0.12.0
