name: atom_dart
version: 0.0.1
description: An experimental Dart plugin for Atom.
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/atom-dartlang-experimental

environment:
  sdk: '>=1.0.0 <2.0.0'

#dependencies:
#  lib_name: any
dev_dependencies:
  test: any
