name: atom_dartlang
version: 0.7.1
description: A Dart plugin for Atom.
homepage: https://github.com/dart-atom/dartlang

environment:
  sdk: '>=1.9.0 <2.0.0-dev.infinity'

dependencies:
  analysis_server_lib: ^0.1.2+2
  atom:
    git: https://github.com/dart-atom/atom.dart.git
    # path: ../atom.dart
  haikunator: ^0.1.0
  logging: ^0.11.0
  markdown: ^0.11.0
  pub_semver: ^1.2.1
  usage: ^1.1.0
  vm_service_lib: ^0.3.0
  yaml: ^2.0.0
  source_maps: "^0.10.4"
  petitparser: "^1.6.1"

dev_dependencies:
  grinder: ^0.8.0+1
  html: ^0.12.0
  test: ^0.12.0
  which: ^0.1.0
